/* ----------------------------------------------------------------------- */
/*                                                                         */
/*   Quartz Arc                                                            */
/*                                                                         */
/*   STM32 F769I Discovery                                                 */
/*                                                                         */
/*   System: Driver                                                        */
/*   Role: RNG Driver                                                      */
/*   Filename: QAD_RNG.hpp                                                 */
/*   Date: 18th November 2021                                              */
/*   Created By: Benjamin Rosser                                           */
/*                                                                         */
/*   This code is covered by Creative Commons CC-BY-NC-SA license          */
/*   (C) Copyright 2021 Benjamin Rosser                                    */
/*                                                                         */
/* ----------------------------------------------------------------------- */

//Prevent Recursive Inclusion
#ifndef __QAD_RNG_HPP_
#define __QAD_RNG_HPP_


//Includes
#include "setup.hpp"


	//------------------------------------------
	//------------------------------------------
	//------------------------------------------


//-------
//QAD_RNG
//
//Singleton class
//Driver class for Random Number Generator (RNG) peripheral, which allows for generation
//of 32bit random numbers.
//This is a singleton class due to only one RNG peripheral existing on the STM32 device,
//preventing potential conflicts if multiple instances of the class were to exist.
class QAD_RNG {
private:

	QA_InitState      m_eInitState;  //Stores whether the driver is currently initialized.
	                                 //A member of the QA_InitState enum defined in setup.hpp

	RNG_HandleTypeDef m_sHandle;     //Handle used by HAL functions to access the RNG peripheral


	//-----------
	//Constructor

	//As this is a private method within a singleton class, this method will be called the
	//first time the static get() method is called.
	QAD_RNG() :
	  m_eInitState(QA_NotInitialized),
		m_sHandle({0}) {}

public:

	//------------------------------------------------------------------------------
  //Delete copy constructor and assignment operator due to being a singleton class
  QAD_RNG(const QAD_RNG& other) = delete;
  QAD_RNG& operator=(const QAD_RNG& other) = delete;

  //-----------------
  //Singleton Methods
  //
  //Used to retrieve a reference to the singleton class
  static QAD_RNG& get(void) {
  	static QAD_RNG instance;
  	return instance;
  }


  //----------------------
  //Initialization Methods

  //Used to initialize the RNG peripheral
  //Returns QA_OK if the initialization is successful, or QA_Fail if initialization fails
  static QA_Result init(void) {
  	return get().imp_init();
  }

  //Used to deinitialize the RNG peripheral
  static void deinit(void) {
  	get().imp_deinit();
  }


  //------------
  //Data Methods

  //Used to retrieve whether the driver class is currently initialized
  //Returns a member of the QA_InitState enum defined in setup.hpp
  static QA_InitState getInitState(void) {
  	return get().m_eInitState;
  }


  //Used to retrieve a 32bit random number generated by the RNG peripheral
  static uint32_t getValue(void) {
  	return get().imp_getValue();
  }

private:

  //NOTE: Please see QAD_RNG.cpp for details of the following methods:

  //----------------------
  //Initialization Methods
  QA_Result imp_init(void);
  void imp_deinit(void);


  //------------
  //Data Methods
  uint32_t imp_getValue(void);

};


//Prevent Recursive Inclusion
#endif /* __QAD_RNG_HPP_ */
